### ISSUE TITLE
Error when running Docker image

### ISSUE THREAD

**Issue by matthew-jurewicz** [brndnmtthws/thetagang#165]
org.w3c.dom.DOMException: jar:file:/root/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:776)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:868)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:563)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:208)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at feature.svg.b.a(b.java:90)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at feature.svg.b.a(b.java:79)
	at feature.svg.b.a(b.java:60)
	at feature.svg.c.a(c.java:66)
	at jtscomponents.plaf.dT.a(dT.java:2405)
	at feature.gfis.component.b.onFontChanged(b.java:109)
	at feature.gfis.component.b.b(b.java:76)
	at feature.gfis.component.b.<init>(b.java:61)
	at feature.tabs.bf.f(bf.java:183)
	at feature.tabs.bf.<init>(bf.java:156)
	at feature.tabs.bg.<init>(bg.java:437)
	at jclient.qm.b(qm.java:847)
	at jclient.qm.eF(qm.java:831)
	at jclient.qm.cn(qm.java:978)
	at trader.tab.bc.cm(bc.java:1532)
	at trader.tab.bc.<init>(bc.java:1522)
	at jclient.qk.<init>(qk.java:216)
	at jclient.ql.<init>(ql.java:492)
	at jclient.qm.<init>(qm.java:513)
	at jclient.qm.<init>(qm.java:509)
	at feature.mainwin.B.a(B.java:257)
	at feature.mainwin.B.a(B.java:139)
	at feature.mainwin.v.a(v.java:175)
	at trader.common.factory.U.a(U.java:249)
	at trader.common.factory.U.a(U.java:216)
	at feature.mainwin.B.a(B.java:173)
	at trader.tab.g.a(g.java:1227)
	at trader.common.factory.b.a(b.java:1509)
	at trader.common.factory.b.c(b.java:1524)
	at trader.common.factory.b.b(b.java:1583)
	at trader.common.factory.b.b(b.java:1467)
	at jclient.f7.b(f7.java:3778)
	at twslaunch.jutils.as.a(as.java:713)
	at jclient.f7.a(f7.java:3776)
	at jclient.f7.a(f7.java:2953)
	at feature.welcome.f.run(f.java:501)
	at feature.welcome.e.run(e.java:509)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR: null
Enclosed Exception:
jar:file:/root/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4

**Comment by brndnmtthws** [comment]
Well that's a strange one. Have you tried using the [sample config.ini](https://github.com/brndnmtthws/thetagang/blob/main/ibc-config.ini) from the repo? Also, check that you have `gateway = true` in your [`thetagang.toml` like this](https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L94).

**Comment by matthew-jurewicz** [comment]
OK there is no error now, but it doesn't look like it's doing anything but printing the config.

**Comment by brndnmtthws** [comment]
Check the IBC log, which should be written out to `ibc.log` by default (again, defined in `thetagang.toml`). Common issues are the wrong credentials, bad settings, API port not enabled, wrong API port, networking issues, etc.

**Comment by matthew-jurewicz** [comment]
I don't see a log file being created (/ibc/ib_insync.log), so I'm not sure there's any output

**Comment by brndnmtthws** [comment]
If you're running it with Docker, you need to make sure the log is being written out to somewhere you can grab it, i.e., to a volume. In my case, I mount the volume at `/ibc` inside the container, and I changed the logfile path to `/ibc/ibc.log`. So my docker command looks like:

```console
$ docker run -v ~/ibc:/ibc ...
```

And my `thetagang.toml` looks like:

```toml
[ib_insync]
logfile = '/ibc/ibc.log'
```

Alternatively you can jump inside the container with `docker exec -it <container> /bin/bash` and fetch the log that way.
