### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by chrisbgp** [brndnmtthws/thetagang#180]
Digest: sha256:6b3cd04158c888e7a584793cfaf701d17dc8498d4c9c818ce03f815e6e693711
Status: Downloaded newer image for brndnmtthws/thetagang:latest
+ export DISPLAY=:1
+ DISPLAY=:1
+ exec /usr/local/bin/thetagang --config /etc/thetagang/thetagang.toml
+ Xvfb :1 -ac -screen 0 1024x768x24
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/schema.py", line 396, in validate
    nvalue = Schema(svalue, error=e, ignore_extra_keys=i).validate(value)
  File "/usr/local/lib/python3.7/dist-packages/schema.py", line 417, in validate
    raise SchemaWrongKeyError(message, e.format(data) if e else None)
schema.SchemaWrongKeyError: Wrong key 'RaiseRequestErrors' in {'gateway': True, 'ibcPath': '/opt/ibc', 'tradingMode': 'paper', 'RaiseRequestErrors': False, 'password': 'demo', 'userid': 'demo', 'ibcIni': '/etc/thetagang/config.ini', 'javaPath': '/opt/java/openjdk/bin'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/thetagang", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/main.py", line 35, in cli
    start(config)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/thetagang.py", line 27, in start
    validate_config(config)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/config.py", line 120, in validate_config
    schema.validate(config)
  File "/usr/local/lib/python3.7/dist-packages/schema.py", line 400, in validate
    raise SchemaError([message] + x.autos, [e.format(data) if e else None] + x.errors)
schema.SchemaError: Key 'ibc' error:
Wrong key 'RaiseRequestErrors' in {'gateway': True, 'ibcPath': '/opt/ibc', 'tradingMode': 'paper', 'RaiseRequestErrors': False, 'password': 'demo', 'userid': 'demo', 'ibcIni': '/etc/thetagang/config.ini', 'javaPath': '/opt/java/openjdk/bin'}

**Comment by brndnmtthws** [comment]
You can workaround this by commenting out the `RaiseRequestErrors` config param, or updating to the latest Docker image.

**Comment by chrisbgp** [comment]
Thanks! However this introduced a new error (latest image):

Traceback (most recent call last):
  File "/usr/local/bin/thetagang", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/main.py", line 35, in cli
    start(config)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/thetagang.py", line 128, in start
    ibc = IBC(981, **ibc_config)
TypeError: __init__() got an unexpected keyword argument 'RaiseRequestErrors'

Does not matter if I set RaiseRequestErrors true or false in the config file.

**Comment by chrisbgp** [comment]
Thank you! Working fine now.
