### ISSUE TITLE
Error when running Docker

### ISSUE THREAD

**Issue by akh64bit** [brndnmtthws/thetagang#181]
I am trying to run the Docker Image without changing any params. I just entered my login info in the .toml file and config.ini
and I am getting the following error. This is on IBKR paper trading account.
*******************************************************************************************************
_**+ export DISPLAY=:1
+ DISPLAY=:1
+ exec /usr/local/bin/thetagang -c /etc/thetagang/thetagang.toml
+ Xvfb :1 -ac -screen 0 1024x768x24
Config:

  Account details:
    Number                   = -
    Cancel existing orders   = True
    Margin usage             = 0.5 (50.0%)
    Market data type         = 1

  Roll options when either condition is true:
    Days to expiry          <= 15 and P&L >= 0.0 (0.0%)
    P&L                     >= 0.9 (90.0%)

  When contracts are ITM:
    Roll puts               = False
    Roll calls              = True

  Write options with targets of:
    Days to expiry          >= 45
    Default delta           <= 0.3
    Maximum new contracts    = 15
    Minimum open interest    = 10

  Symbols:
      SPY weight = 0.40 (40.0%), delta = 0.30p, 0.30c
      QQQ weight = 0.30 (30.0%), delta = 0.50p, 0.30c, call strike >= $100.00, put strike <= $1000.00
      TLT weight = 0.20 (20.0%), delta = 0.40p, 0.40c
     ABNB weight = 0.05 ( 5.0%), delta = 0.30p, 0.30c
    BRK.B weight = 0.05 ( 5.0%), delta = 0.30p, 0.30c

Traceback (most recent call last):
  File "/usr/local/bin/thetagang", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/main.py", line 35, in cli
    start(config)
  File "/usr/local/lib/python3.7/dist-packages/thetagang/thetagang.py", line 128, in start
    ibc = IBC(981, **ibc_config)
TypeError: __init__() got an unexpected keyword argument 'RaiseRequestErrors'**_

**Comment by akh64bit** [comment]
Thank you so much Brenden.
Inside the thetagang folder, I get ib_insync.log (Not sure this is same as ibc.log). This file is empty.
If ibc.log is different from ib_insync.log, could you point me where to find it?

Thanks in advance.

Regards.
