### ISSUE TITLE
java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by a1exus** [brndnmtthws/thetagang#238]
Hello World!

I'm trying to follow [Up and running with Docker](https://github.com/brndnmtthws/thetagang#up-and-running-with-docker), yet running into issue that can't pass(

the actual error:

```
No protocol specified
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-01-31 05:27:45:029 IBC: An exception has occurred:
java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
        at ibcalpha.ibc.IbcTws.createToolkitListener(Unknown Source)
        at ibcalpha.ibc.IbcTws.load(Unknown Source)
        at ibcalpha.ibc.IbcGateway.main(Unknown Source)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

step I took:

```
$ mkdir ~/thetagang
$ cd ~/thetagang
$ curl -Lq https://raw.githubusercontent.com/brndnmtthws/thetagang/main/thetagang.toml -o ~/thetagang/thetagang.toml
$ curl -Lq https://raw.githubusercontent.com/brndnmtthws/thetagang/main/ibc-config.ini -o ~/thetagang/config.ini
$ docker run --rm -i --net host \
    -v ~/thetagang:/etc/thetagang \
    brndnmtthws/thetagang:main \
    --config /etc/thetagang/thetagang.toml
+ export DISPLAY=:1
+ DISPLAY=:1
+ Xvfb :1 -ac -screen 0 1024x768x24
++ arch
+ export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/jni
+ LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/jni
+ exec /usr/local/bin/thetagang --config /etc/thetagang/thetagang.toml
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
Config:
...
No protocol specified
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-01-31 05:27:45:029 IBC: An exception has occurred:
java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
        at ibcalpha.ibc.IbcTws.createToolkitListener(Unknown Source)
        at ibcalpha.ibc.IbcTws.load(Unknown Source)
        at ibcalpha.ibc.IbcGateway.main(Unknown Source)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Please advise.

**Comment by brndnmtthws** [comment]
Do you already have an X11 server running somewhere? Are there multiple instances of the same docker container running (check with `docker ps`)?

**Comment by a1exus** [comment]
@brndnmtthws thank you for trying to help me, i really appreciate your time)

I've got the error while trying to run Docker' container on my Chromebook, just in case it is not compatible, I also tried to run same container on my Mac as well:

```
% tail -7 ib_insync.log
2023-01-31 19:27:08,640 ib_insync.IBC INFO Starting
2023-01-31 19:27:38,656 ib_insync.client INFO Connecting to 127.0.0.1:7497 with clientId 1...
2023-01-31 19:27:38,658 ib_insync.client INFO Disconnecting
2023-01-31 19:27:38,659 ib_insync.client ERROR API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 7497)")
2023-01-31 19:27:38,660 ib_insync.client ERROR Make sure API port on TWS/IBG is open
2023-01-31 19:27:38,661 ib_insync.IBC INFO Terminating
2023-01-31 19:27:41,024 ib_insync.IBC INFO Starting
% 
```

I didn't get the same error, however I got the one pasted above..

Please advise.
Thanks again!

**Comment by brndnmtthws** [comment]
You're going to need to debug it a little more. Check the logs thoroughly for error messages to see what's going on.

**Comment by a1exus** [comment]
@brndnmtthws - 

> Check the logs thoroughly for error messages to see what's going on.

Could you please explain a bit more? Which logs do should I be checking? The container stdout (logs) doesn't produce any errors, just the python script output, how can I debug it more?

Thanks again!

**Comment by a1exus** [comment]
```
alexus@mbp ~ % docker exec -it vigilant_hypatia tail -0f /root/Jts/launcher.log
2023-02-01 02:48:56.051 [TH] INFO  [JTS-Main] - ------------------------------- IB GATEWAY RESTART --------------------------------
2023-02-01 02:48:56.055 [TH] INFO  [JTS-Main] - installer version: unknown, installer type: standalone, install dir: 'null', Jts dir: '/root/Jts', VM options file: 'null'
2023-02-01 02:48:56.068 [TH] INFO  [JTS-Main] - Verifying environment [entryPoint=IBGATEWAY_STANDALONE]...
2023-02-01 02:48:56.087 [TH] INFO  [JTS-Main] - Install4jAutoUpdateService initialized [props=LauncherProperties[updateDownloadUrl=null,skipUpdateCheck=false,nightlyEnabled=false,channelNameArg=null,channelName=latest,channelChanged=false,jtsConfigDir=null,apiPort=null,sessionId=null,installDir=null,exeName=null]].
2023-02-01 02:48:56.091 [TH] INFO  [JTS-Main] - PROXY Installed custom selector
2023-02-01 02:48:56.097 [TH] INFO  [JTS-Main] - useSsl=true,FIX endPoint=null:4001
2023-02-01 02:48:56.213 [TH] INFO  [JTS-Main] - Setting custom timezone: Africa/Abidjan
2023-02-01 02:48:56.217 [TH] INFO  [JTS-Main] - LOCALE: Property locale_to_use=null
2023-02-01 02:48:56.222 [TH] INFO  [JTS-Main] - LOCALE: JTS Locale=en_US  country=United States  variant=
2023-02-01 02:48:56.223 [TH] INFO  [JTS-Main] - Region: Custom
2023-02-01 02:48:56.224 [TH] WARN  [JTS-Main] - The locales jar directory resolved to '/root/Jts/jars' ('installDir' system property is not set).
2023-02-01 02:48:56.224 [TH] WARN  [JTS-Main] - The locales jar directory resolved to '/root/Jts/jars' ('installDir' system property is not set).
2023-02-01 02:48:56.224 [TH] INFO  [JTS-Main] - Locale from ini: en
2023-02-01 02:48:56.225 [TH] INFO  [JTS-Main] - Locale=en_US  country=United States  variant=
2023-02-01 02:48:56.228 [TH] INFO  [JTS-Main] - prohibiting class lookup [twslaunch.ji18n.LauncherLanguage]
2023-02-01 02:48:56.230 [TH] INFO  [JTS-Main] - prohibiting class lookup [twslaunch.ji18n.LauncherLanguage_en]
2023-02-01 02:48:56.231 [TH] INFO  [JTS-Main] - prohibiting class lookup [twslaunch.ji18n.LauncherLanguage_en_US]
2023-02-01 02:48:56.231 [TH] INFO  [JTS-Main] - LOCALE:  type: launcher intended: en_US actual:  size: 485
2023-02-01 02:48:56.232 [TH] INFO  [JTS-Main] - settings dir: '/root/Jts'
2023-02-01 02:48:56.386 [TH] INFO  [JTS-Main] - LauncherFontUpdater: simulatehighdefscreen=false
2023-02-01 02:48:56.390 [TH] INFO  [JTS-Main] - LauncherFontUpdater: Screen dimensions=1024x768
2023-02-01 02:48:56.390 [TH] INFO  [JTS-Main] - LauncherFontUpdater: highres=false
2023-02-01 02:48:56.390 [TH] INFO  [JTS-Main] - LauncherFontUpdater: FontSize=16
2023-02-01 02:48:56.390 [TH] INFO  [JTS-Main] - initPreUI() - entry
2023-02-01 02:48:56.400 [TH] INFO  [JTS-Main] - Build 10.19.1j, Jan 11, 2023 6:06:40 PM
2023-02-01 02:48:56.430 [TH] INFO  [JTS-Main] - LookAndFeelChangedListener installed
2023-02-01 02:48:56.433 [TH] INFO  [JTS-Main] - JtsLookAndFeel initialized
2023-02-01 02:48:56.848 [TH] INFO  [JTS-Main] - Current LAF: TWS LAF
2023-02-01 02:48:56.848 [TH] INFO  [JTS-Main] - initPreUI() - exit
2023-02-01 02:48:57.305 [TH] INFO  [AWT-EventQueue-0] - Default timezone:Africa/Abidjan
2023-02-01 02:48:57.308 [TH] INFO  [AWT-EventQueue-0] - Starting GstatMessageMgr...
2023-02-01 02:48:57.309 [TH] WARN  [JTS-GstatMessageMgr-6] - Misc URLs have not been received. Resending request...
2023-02-01 02:48:57.357 [TH] INFO  [AWT-EventQueue-0] - Started on 20230201-02:48:57
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - Default timezone:Africa/Abidjan name:Greenwich Mean Time dst:0
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - java version = 17.0.4
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - sun.arch.data.model = 64
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - os = Linux
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - os version = 5.15.49-linuxkit
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - os architecture = 32
2023-02-01 02:48:57.358 [TH] INFO  [AWT-EventQueue-0] - runtime = OpenJDK Runtime Environment
2023-02-01 02:48:57.359 [TH] INFO  [AWT-EventQueue-0] - vendor = Eclipse Adoptium
2023-02-01 02:48:57.359 [TH] INFO  [AWT-EventQueue-0] - vm name = OpenJDK 64-Bit Server VM
2023-02-01 02:48:57.359 [TH] INFO  [AWT-EventQueue-0] - username = 'Unknown'
2023-02-01 02:49:01.091 [TH] INFO  [JTS-DeadlockMonitor-2] - Memory:total=786,432KB free=738,110KB HeapUsage: Max=786,432KB used=46,654KB committed=65,536KB NonHeapUsage: Max=0KB used=56,500KB committed=58,496KB
2023-02-01 02:49:02.096 [TH] INFO  [JTS-DeadlockMonitor-2] - CPU:cur=0.11% avg=0.11% 30 min avg=0.11% 10 min avg=0.11% 5 min avg=0.11% 1 min avg=0.11%
GC:called=6 times CPU used=0.07%
Finalizer:cur=0.00% avg=0.00% 30 min avg=0.00% 10 min avg=0.00% 5 min avg=0.00% 1 min avg=0.00%
Threads Count:curr live=28 curr daemon=17
```

IB GATEWAY RESTART keeps on restarting...

**Comment by brndnmtthws** [comment]
Are you trying to use a demo account? I don't think that will work, you need to login to a valid account.

PS: Careful not to leak your account details on here.

**Comment by a1exus** [comment]
> Are you trying to use a demo account? I don't think that will work, you need to login to a valid account. A paper account is fine, it just needs to actually exist.

right, sorry.. the first time when i ran "ps" command i had demo account in there, which i then updated to my actual account and left my last comment where ib gateway keeps on restarting..

> PS: Careful not to leak your account details on here.

right, thank you)

**Comment by a1exus** [comment]
> Are you using the [sample config.ini](https://github.com/brndnmtthws/thetagang/blob/main/ibc-config.ini)?

yes, with updated `IbLoginId`, `IbPassword` and `TradingMode` (paper)

```
alexus@mbp thetagang % diff config.ini bak/config.ini | cut -d= -f1
79c79
< IbLoginId
---
> IbLoginId
103c103
< IbPassword
---
> IbPassword
161c161
< TradingMode
---
> TradingMode
alexus@mbp thetagang %
```

**Comment by a1exus** [comment]
FYI: at very least, one cannot use "IBKR Lite" and must use "IBKR Pro" instead
